version: '3.7'
services:
  redis:
    container_name: redis
    image: 'redis:alpine'
    command: redis-server --requirepass password
    ports:
      - '6379:6379'

  redis-commander:
    container_name: redis-comander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    depends_on:
      - redis

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: general
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
